Fix build error caused by enabled extra compiler warnings
 nmea.c:257:16: error: comparison between signed and
     unsigned integer expressions [-Werror=sign-compare]

Signed-off-by: Petr Štetiar <ynezz@true.cz>